boss:
  image: 'openmajiang-boss:latest'
  restart: always
  container_name: boss
  hostname: boss
  mem_limit: 1G
  memswap_limit: 1G
  expose:
      - '11000/tcp'
      - '11001/tcp'
      - '11002/tcp'
  links:
   - mysql
scene:
  image: 'openmajiang-scene:latest'
  restart: always
  container_name: scene
  hostname: scene
  mem_limit: 1G
  memswap_limit: 1G
  expose:
     - '12000/tcp'
  links:
     - mysql
     - boss
gateway:
  image: 'openmajiang-gateway:latest'
  restart: always
  container_name: gateway
  hostname: gateway
  mem_limit: 1G
  memswap_limit: 1G
  ports:
    - '8010:8010/tcp'
  links:
    - scene
    - boss
client:
  image: 'openmajiang-client:latest'
  restart: always
  container_name: client
  hostname: client
  mem_limit: 1G
  memswap_limit: 1G
  ports:
    - '8081:8080/tcp'
  links:
       - mysql
       - boss
       - gateway
mysql:
  hostname: mysql
  image: mysql:5.7
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 111111
    MYSQL_DATABASE: boss
  restart: always
  labels:
    aliyun.logs: /var/log/mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
